### PR TITLE
Multi-region banners w/ audio + Improvements

### PR DESCRIPTION
**Pull request by ohyocbz**
- I did try my best in finding and editing the highest quality logos and audios as possible, especially to non-English game releases since they are hard to find.

- Some banners were already uploaded here by the original poster but I made some minor adjustments such as removing thin white lines that are visible on darker backgrounds, turning blurred/low quality banners to HD while maintaining the integrity from the original logo, etc. _The credit work is still named to them and not me as a whole._

- This is only part 1. There are more parts to upload but it'll take quite some time to finish.

1. Animal Crossing: Wild World (INT) ~
2. Oide yo Dōbutsu no Mori (JPN)
3. Nolleooseyo Dongmurui Sup (KOR)
4. Assassin's Creed: Altaïr's Chronicles (INT) *
5. Assassin's Creed II: Discovery (INT) *
6. Bratz: Forever Diamondz (INT)
7. Gyakuten Kenji (JPN)
8. Gyakuten Kenji 2 (JPN) ~^
9. Harvest Moon: The Tale of Two Towns (INT) ^
10. Bokujou Monogatari: Futago no Mura (JPN) ^
11. Final Fantasy III (INT+JPN) *
12. Final Fantasy IV (INT+JPN) *
13. Final Fantasy: The 4 Heroes of Light (INT) ^
14. Hikari no 4 Senshi: Final Fantasy Gaiden (JPN) ^

**NOTES:**
" ~ " Improved logo. Credits to the original owner who first submitted.
" * " No banner sound.
" ^ " Added a new banner sound that wasn't uploaded before.

### CODE REVIEW

**Comment by lifehackerhansol** [comment]
Just out of curiosity (not trying to call you out or anything, but this *is* a lot of banners so I want to be sure)

There are a lot of these, you did test them all, yes?

**Comment by ohyocbz** [comment]
yes i did test them one by one (even the region roms) today before finally uploading them here.

**Comment by lifehackerhansol** [comment]
Thank you for your efforts. That's all I ask. Great work.

I'll do a last minute check when I get home and merge them.

**Comment by ohyocbz** [comment]
hello! i just noticed there's an unwanted folder i uploaded so i have to remove it

- YB9P (redirected as Bratz: The Movie)
idk why gamefaqs displayed it as french ver. for Bratz: Forever Diamondz but the original code was AVDF, hence AVD banner will be used normally]

**Comment by lifehackerhansol** [comment]
What's up with the assets/YF4/YF4 (1).png and etc? (the ones with what appears to be duplicate file name thing done by Windows)

**Comment by ohyocbz** [comment]
> What's up with the assets/YF4/YF4 (1).png and etc? (the ones with what appears to be duplicate file name thing done by Windows)

oh that. i haven't decided which banners shall be displayed on the 3ds but all of them are working alright. is there anything need to delete some files?

**Comment by lifehackerhansol** [comment]
It won't break the app, but I personally would prefer to stick to one. You can always PR again if you think it is not good enough and want to switch to something else.

**Comment by lifehackerhansol** [comment]
Sorry about the delay, and thanks for the contribution!

**Pull request merged**
